---
title: "cleanNLP and spaCyr"
description: |
  A short description of the post.
author:
  - name: Kristina Becvar
    url: https://kbec19.github.io/NYT-Analysis/
date: 2022-05-01
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Other Types of Analysis
Utilizing the cleanNLP package:
As usual, I am struggling to get this to work due to my inexperience with the python backend. What worked for me last time I ran this in a previous tutorial was no longer working, so I had to uninstall my miniconda installation and re-install it, but eventually it initialized so I could run the “cnlp_annotate” function.

Show code
cnlp_init_udpipe()

#first the main headlines

main_tibble <- as_tibble(main_headlines) %>%
  select(c("doc_id", "text"))
main_tibble <- utf8::as_utf8(main_tibble$text)

annotated_main <- cnlp_annotate(main_tibble)

#then the print headlines

print_tibble <- as_tibble(print_headlines) %>%
  select(c("doc_id", "text"))
print_tibble <- utf8::as_utf8(print_tibble$text)

annotated_print <- cnlp_annotate(print_tibble)

Using spaCyr
For Main Headlines
Show code
parsed_main <- spacy_parse(main_headlines,
                           lemma = TRUE,
                           entity = TRUE,
                           nounphrase = TRUE,
                           sentiment = TRUE,
                           additional_attributes = c("is_punct",
                                                     "is_stop",
                                                     "is_currency",
                                                     "is_digit",
                                                     "is_quote")) %>%
  as_tibble %>%
  select(-sentence_id)

head(parsed_main)

summary(parsed_main)

For Print Headlines
Show code
parsed_print <- spacy_parse(print_headlines,
                           lemma = TRUE,
                           entity = TRUE,
                           nounphrase = TRUE,
                           additional_attributes = c("is_punct",
                                                     "is_stop",
                                                     "is_currency",
                                                     "is_digit",
                                                     "is_quote",
                                                     "sentiment")) %>%
  as_tibble %>%
  select(-sentence_id)

head(parsed_print)

summary(parsed_print)

